### PR TITLE
Alt line fit

### PR DESCRIPTION
**Pull request by Peterdha**
Hi Kevin, hope you get this...
added 
```
        :param smooth: one of {"interp1d", "polynomial"}
        :type smooth: string
``` 
it works from my side
haven't done any extensive testing though...

### CODE REVIEW

**Comment by arvkevi** [comment]
This PR addresses the "bumpy" line in #25

**Comment by arvkevi** [comment]
@Peterdha now that this passes, do you want to update the `README` with a description of why `interp_method` was added along with a demonstration (perhaps from #25)? If not, I'm happy to do so.

**Comment by arvkevi** [comment]
Thanks for the contribution @Peterdha 👍

**Comment by Peterdha** [comment]
Thanks Kevin :-)

**Pull request merged**
